language: node_js
node_js:
- 8
deploy:
  provider: heroku
  api_key:
    master:
        secure: DAMPDdzMdPVwXQYvcXldFGEqghV3HH2COMSnuD536xV/hlu1H0ItTGEofI5Iwha9ABXlikAePTKAAG2xswxmQCyQjGfxNe2qHW0JG4+buI+epvOmkiRSB3YJQR7r+J8Fq4nTXdPRKmreyftFcsowLoTIGofdWhu7HXG03gAD1OfBNsT2MIfLxIiKQgMAmLI7lFzBiwtvG56RgRpmNMkfNGsTvyQZUUtxSdesZdl5IaKZdXjW7wJEI6p+RZ5PyZ/oQJmzCtz99ucvuNDvZYEo+2ZCgnFDsZezxgOA3BHuLK79MWX6x6OpUELljgLfSgIN9VWaKodLthl9AHrgDogxyGwWJY1ECXGVIXDhTt+g3EYkp7i7JmZCccktJanRHgioNNNYn+UU6kJTqTyfAv9npplItOV2HHZ6eBhnaR/fQL0+O7pc8pKUuz18s9BMAl9j8tG+A4jtJ+RQUm78Ol0afJiAU+v8srkU4C3xiOUO2b6rIM/Aaq0N0/dcHUjrpcw678rVw/6HOkWPojj+7IUp9pRvmZlabhn8hzdpQB6WqnNaOeDXv10uqgIPFBc2ogP6HRuJim0x3HqVfpBFjp5MU17In+Z6shKrodsFI2rCPFcF5E8CIlQwmPwM2+TsM6cumO4vYBrow2bysYLnDXxrxvUQJjDjngiQWSKEp7diuww=
        
    develop:
        secure: EYWEHgqXUxe/b3mZUuBZgx2UPLctL9f+37m5JbcN2HZF+mwV51Aoh+Qv4syw//vc2JmPCYVioUW7Oxv0fQROFzY8AVIYPqF/HgtHov6UwCGiXheizQwyhq38hlg8l5tplhSfXKf41V1Im61+bnQc6a3I4C/jNBioFMlp9MryVkVaAitX6ryshj7hxRpYX21SU6t8vijIMcbvXjyqhYl9H3XyXlsRPg72aV3pbZtkjAOFLxt8KdI5UVraJvS3GMIbkDPFbyrI0p6fDONCjJ+bOzXFh1r1hq+wEYE1rmIQDT9vNHpSkft2ta/1Z27xW08H5Tfy3hftMvEPMI1uFIQsFc+ei96N8HrHZYIi+ympGsRWHULE8VKMeBD8erRgq6/JWJVPRszF/YGKhDNE+6cPKgR5X44j9JraczxWh0qz8XouMYRy6ZRsOlBWGgQnrpwcaAE4xP5JtX+WePNj/AT8r+HzV3WMKstUX+jchPvUaHa6uI4SEDTlOHO1hCaT8UEgSFMFbZnjMGkT45bu1rhjP8VpXZ9sSArUOGwBWMU+rD7MeV9i2N2GrLZpHNqDNfFs/yUYGQkVlPv22pr/Cu2c0q19YI3179leuaK/yy6QsgzwAs3CHjzY/kGWmeZZY2yGWEeNatrtqAgvyNOVvjZXCde0bqaPT78chIIsDGuJ17Y=
  app: 
    master: master-heroku-souchef
    develop: sous-chef-assistant
notifications:

  slack: ser515-fall2018:0ORqJzFF4lb4O5SZd8xTitJJ
  email:
    recipients:
      - swdunnin@asu.edu
      - sparanj2@asu.edu
      - rkhatun@asu.edu
      - dlahtine@asu.edu
      - pahorton@asu.edu
      - trevor4e@gmail.com
  on_success: change # default: always
  on_failure: always # default: always

